### ISSUE TITLE
Parsing error from Swagger Petstore example - OpenAPIKit incorrectly requires `type` keyword

### ISSUE THREAD

**Issue by hooliooo** [mattpolzin/OpenAPIKit#50] opened 2020-04-17 15:58 UTC
Hi there,
I'm really looking forward to this library and I wanted to check it out. I used the yaml defined in https://editor.swagger.io/?_ga=2.63340079.1270489904.1587138107-483118911.1586550581#. The Petstore example with `openapi: 3.0.1` and came across these errors:

```
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid YAML.", underlyingError: Optional(OpenAPIKit.OpenAPI.Error.Decoding.Document(context: OpenAPIKit.OpenAPI.Error.Decoding.Document.Context.path(OpenAPIKit.OpenAPI.Error.Decoding.Path(path: OpenAPIKit.OpenAPI.Path(components: ["pet", "{petId}"]), context: OpenAPIKit.OpenAPI.Error.Decoding.Path.Context.endpoint(OpenAPIKit.OpenAPI.Error.Decoding.Operation(endpoint: OpenAPIKit.OpenAPI.HttpVerb.post, context: OpenAPIKit.OpenAPI.Error.Decoding.Operation.Context.request(OpenAPIKit.OpenAPI.Error.Decoding.Request(context: OpenAPIKit.OpenAPI.Error.Decoding.Request.Context.neither(Either failed to decode any of its types at: "paths//pet/{petId}/post/requestBody/content/application/x-www-form-urlencoded/schema"

JSONReference<JSONSchema> could not be decoded because:
Error Domain=NSCocoaErrorDomain Code=4865 "No value associated with key CodingKeys(stringValue: "$ref", intValue: nil) ("$ref")." UserInfo={NSDebugDescription=No value associated with key CodingKeys(stringValue: "$ref", intValue: nil) ("$ref")., NSCodingPath=(
    "CodingKeys(stringValue: \"paths\", intValue: nil)",
    "AnyCodingKey(stringValue: \"/pet/{petId}\", intValue: nil)",
    "CodingKeys(stringValue: \"post\", intValue: nil)",
    "CodingKeys(stringValue: \"requestBody\", intValue: nil)",
    "CodingKeys(stringValue: \"content\", intValue: nil)",
    "AnyCodingKey(stringValue: \"application/x-www-form-urlencoded\", intValue: nil)",
    "CodingKeys(stringValue: \"schema\", intValue: nil)"
)}

JSONSchema could not be decoded because:
Error Domain=NSCocoaErrorDomain Code=4865 "No value associated with key HintCodingKeys(stringValue: "type", intValue: nil) ("type")." UserInfo={NSDebugDescription=No value associated with key HintCodingKeys(stringValue: "type", intValue: nil) ("type")., NSCodingPath=(
    "CodingKeys(stringValue: \"paths\", intValue: nil)",
    "AnyCodingKey(stringValue: \"/pet/{petId}\", intValue: nil)",
    "CodingKeys(stringValue: \"post\", intValue: nil)",
    "CodingKeys(stringValue: \"requestBody\", intValue: nil)",
    "CodingKeys(stringValue: \"content\", intValue: nil)",
    "AnyCodingKey(stringValue: \"application/x-www-form-urlencoded\", intValue: nil)",
    "CodingKeys(stringValue: \"schema\", intValue: nil)"
)}), relativeCodingPath: [CodingKeys(stringValue: "content", intValue: nil), AnyCodingKey(stringValue: "application/x-www-form-urlencoded", intValue: nil), CodingKeys(stringValue: "schema", intValue: nil)])), relativeCodingPath: [CodingKeys(stringValue: "requestBody", intValue: nil), CodingKeys(stringValue: "content", intValue: nil), AnyCodingKey(stringValue: "application/x-www-form-urlencoded", intValue: nil), CodingKeys(stringValue: "schema", intValue: nil)])), relativeCodingPath: [CodingKeys(stringValue: "post", intValue: nil), CodingKeys(stringValue: "requestBody", intValue: nil), CodingKeys(stringValue: "content", intValue: nil), AnyCodingKey(stringValue: "application/x-www-form-urlencoded", intValue: nil), CodingKeys(stringValue: "schema", intValue: nil)])), codingPath: [CodingKeys(stringValue: "paths", intValue: nil), AnyCodingKey(stringValue: "/pet/{petId}", intValue: nil), CodingKeys(stringValue: "post", intValue: nil), CodingKeys(stringValue: "requestBody", intValue: nil), CodingKeys(stringValue: "content", intValue: nil), AnyCodingKey(stringValue: "application/x-www-form-urlencoded", intValue: nil), CodingKeys(stringValue: "schema", intValue: nil)]))))
```

I'm not sure about the first error but the second and third error: seems like it's expecting a `$ref` or `type` key where there isn't one.

**Comment by mattpolzin** [comment] 2020-04-21 22:33
Sorry for the delayed reply. I somehow missed this issue being reported until today.

Before I address the issue you found, I'll mention that the error you posted would _hopefully_ be a bit easier to reason about if you passed it to `OpenAPI.Error` as in:
```swift
do {
  try decoder.docode(...)
} catch {
  let openAPIError = OpenAPI.Error(from: error)
  print(openAPIError.localizedDescription)
  print(openAPIError.codingPathString)
}
```

Regardless, I can see the problem and what you've uncovered is a bug with OpenAPIKit. OpenAPIKit currently requires the JSON Schema `type` keyword for all OpenAPI Schemas. I had interpreted the JSON Schema as requiring this keyword, when in reality I see now that it does not.

The part of the Pet Store example that fails is:
```yaml
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: string
                  description: Updated name of the pet
                status:
                  type: string
                  description: Updated status of the pet
```

It fails because the `schema` has a `properties` object but no definition of `type: object`. As I noted above, after re-reading the JSON Schema specification I believe this is a bug with OpenAPIKit so I am going to rename your ticket and use it to track the bug.

If you wish to get past this error as-is, the following snippet dropped in place of the above one would parse successfully (note the `type: object` under `schema`):
```yaml
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Updated name of the pet
                status:
                  type: string
                  description: Updated status of the pet
```

**Comment by mattpolzin** [comment] 2020-04-22 01:24
This bug will be fixed in the next release.

**Closed** 2020-04-22 01:57 UTC
Labels: bug

**Comment by mattpolzin** [comment] 2020-04-22 02:08
This bug is fixed in version 0.29.0. Please let me know if it still causes you any trouble!

**Comment by hooliooo** [comment] 2020-04-22 19:16
Thanks for the feedback!

**Comment by hooliooo** [comment] 2020-04-22 19:58
Continuing on the Pet store example. New error in a different part of the OpenAPI yml

`Found neither a $ref nor a Parameter in .parameters[0] for the **GET** endpoint under /store/order/{orderId}. `

**Comment by mattpolzin** [comment] 2020-04-22 20:15
Interesting. I thought I pulled the pet store example into the compatibility suite and confirmed it parsed but there must be more than one version of it (I snagged one from some git repository owned by Swagger). 

Please do create a new issue as I am guessing this is at least a subtly different bug but I will have to take a look again tonight. 

Thank you for reporting the roadblocks you are hitting!
